### ISSUE TITLE
Precision of scores

### ISSUE THREAD

**Issue by mayanks43** [DateDocta/DatingGame#1]
Hey DateDocta,

First of all, great job with the architecture.

The architecture requires "All scores will have four digits of precision (exactly)". Could you make sure that's true?

I am getting abominations like "0.09999999999999998" for "0.1" due to limitations of floating points on computers. Something like [this](https://github.com/DateDocta/DatingGame/blob/master/coffeescripts/game.coffee#L167) should do it I  guess.

**Comment by DateDocta** [comment]
Sure thing.  Working on that now

**Comment by DateDocta** [comment]
Pushed those changes, should we working. Pull and try again and if you noticed the fix we can close this.

**Comment by mayanks43** [comment]
Looks good.
