### ISSUE TITLE
Server only allows 19 candidates for the matchmaker

### ISSUE THREAD

**Issue by mayanks43** [DateDocta/DatingGame#2]
[This](https://github.com/DateDocta/DatingGame/blob/master/coffeescripts/game.coffee#L108) line should be "is 21" as you use up one turn in sending the initial 20.

**Comment by DateDocta** [comment]
My matchmaker client sends 20 and I believe that it should not be 21 there.  Whenever we hit that line, the turn will indicate however many matchmaker candidates we have received to that point.  So when turn is 20, we have received 20.  

When we set turn to 1, and then hit that else right above your line, at this point, we have received one matchmaker candidate.  From that point on, we update at the end, so at the point of that line you linked, turn will indicate how many candidates we have received.  I can use a better variable name like candidates received if it helps, but the logic and is working when tested.  Have you had issues trying to send 20?

**Comment by mayanks43** [comment]
ok yeah, you are right. I was sending a candidate after receiving the first 20 and not counting it as one of the 20 candidates.

**Comment by mayanks43** [comment]
Btw this issue still there. I accepted your response in a hurry. But too late now.

**Comment by keeyon2** [comment]
We have tested this and it has been fixed in our testing. We send a correct
amount of confidantes. Have you pulled recently?

**Comment by mayanks43** [comment]
Yeah you are right again. Sorry about the unnecessary noise. I had made the wrong assumption that the matchmaker would receive 40 datapoints. Turns out MM only receives 39. For fortieth candidate, it receives no response as it's quota of additional 20 candidates is complete. Thanks for the quick reply.
