### ISSUE TITLE
Able to send weights whose sum is greater than 1 or less than -1.

### ISSUE THREAD

**Issue by mayanks43** [DateDocta/DatingGame#4]
[This](https://github.com/DateDocta/DatingGame/blob/master/coffeescripts/player.coffee#L24) line only ensures that sum of positive weights is greater than 1 or that of negative weights is less than -1. However, we need the sum of positive weights to be 1 and negative weights to be -1. 
Due to this, I was able to send negative weights that sum to -1.02. 

This can be fixed by adding two more conditions: 
`totalPositiveValue < 1.000000001 and totalNegativeValue > -1.000000001`.

However, using manually entered numbers like that may lead to difference in error tolerance levels in different parts of the code (as has happened [here](https://github.com/DateDocta/DatingGame/blob/master/coffeescripts/game.coffee#L108) and [here](https://github.com/DateDocta/DatingGame/blob/master/coffeescripts/player.coffee#L24). Notice the different number of 9's). So, to ensure consistency, I suggest to create an epsilon (some small number) value in utils.coffee and use that to check equality of float numbers in [this](http://stackoverflow.com/a/1088271) manner.

Therefore, a better check would be: 
`Math.abs(totalPositiveValue - 1) < epsilon and Math.abs(totalNegativeValue + 1) < epsilon.`

[This](https://github.com/DateDocta/DatingGame/blob/master/coffeescripts/game.coffee#L108) could also be changed to: `Math.abs(score - 1) < epsilon`. 

Obviously, the last two changes are at your discretion.

**Comment by DateDocta** [comment]
Very good point.  I think we are going to go with your approach.  Thank you for commenting on this.Could you also list the N and weights you used to get to the sum of -1.02?  I am going to do some testing with all the different approaches

**Comment by mayanks43** [comment]
Well yeah.

Here's a weight list that violates both criterion (N=50).
`-0.58 0.52 0.51 -0.52 0.51 0.51 -0.57 0.55 -0.59 0.55 -0.5 0.53 -0.56 0.53 0.53 -0.57 -0.55 -0.55 -0.56 -0.59 -0.5 -0.56 -0.58 0.54 0.52 0.51 0.55 -0.53 -0.52 0.51 0.53 0.55 0.54 0.55 0.55 -0.6 0.53 0.52 0.54 0.55 0.54 -0.53 0.54 0.53 0.51 0.53 -0.53 0.55 0.55 0.53`
Sum of positive weights = 16.51
Sum of negative weights =  -10.49

I can get crazy max score like 11.7300 with this loophole.

**Comment by DateDocta** [comment]
Thank you for these finds @mayanks43 .  I appreciate it.  I have fixed the is not issue and I have also used an epsilon check to make sure the sum of positive and negative weights are correct.  Feel free to test and verify

**Comment by mayanks43** [comment]
I think 1e-15 (you can directly use the 'e' rep instead of typing 0.000000000000001) is too harsh an epsilon value. Maybe keep it at 1e-6 or 1e-7. 
I am getting error for a positive sum of 1.0000000000000004.

**Comment by DateDocta** [comment]
Cool  Thanks for the check.  Good call.  That has been changed and pushed.

**Comment by mayanks43** [comment]
Sorry to pester you but a few more errors.
Seems just making the epsilon less harsh wasn't enough.
[`@epsilon = 0.000001`](https://github.com/DateDocta/DatingGame/blob/master/coffeescripts/utils.coffee#L6) should be `epsilon: 0.000001`. epsilon becomes undefined in comparisons. 

Also, I didn't know coffeescript was so harsh. 
[`Math.abs(score -1)`](https://github.com/DateDocta/DatingGame/blob/master/coffeescripts/game.coffee#L109) should be `Math.abs(score - 1)` (mind the extra space). Look at the [javascript translation](https://github.com/DateDocta/DatingGame/blob/master/javascripts/game.js#L113) of the previous one.

**Comment by DateDocta** [comment]
@mayanks43 You are the man.  You are helping me out greatly.  We all of a sudden were having issues that we couldn't solve, and you found them.  Thanks for this.  Good call.  We are pushing out those changes now.

**Comment by mayanks43** [comment]
Cool. Closing this.
